# Generated by Django 3.0.8 on 2020-08-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='langauges_learnt',
            field=models.ManyToManyField(blank=True, related_name='knowing_students', to='core.Language'),
        ),
        migrations.AlterField(
            model_name='student',
            name='languages_to_learn',
            field=models.ManyToManyField(blank=True, related_name='learning_students', to='core.Language'),
        ),
    ]
