# Generated by Django 3.0.8 on 2020-09-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='last_activity',
            field=models.CharField(default=models.DateTimeField(auto_now_add=True), max_length=50),
        ),
    ]
