# Generated by Django 3.0.8 on 2020-08-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='note',
            name='note_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
