# Generated by Django 3.0.8 on 2020-08-25 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='trainer',
        ),
    ]
