# Generated by Django 3.0.8 on 2020-09-01 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='student_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.StudentCourse'),
        ),
    ]
