# Generated by Django 3.0.8 on 2020-11-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
