# Generated by Django 3.0.8 on 2020-11-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TellUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('lang_to_learn', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
                ('lang_already', models.CharField(max_length=100)),
                ('preference', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=100)),
            ],
        ),
    ]
