# Generated by Django 3.0.8 on 2020-10-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='forum_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
