# Generated by Django 3.0.8 on 2020-08-25 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_assignment_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='student_course',
        ),
        migrations.AddField(
            model_name='note',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Course'),
        ),
    ]
