# Generated by Django 3.0.8 on 2020-08-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200803_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='languages_known',
            field=models.ManyToManyField(blank=True, related_name='knowing_teachers', to='core.Language'),
        ),
    ]
