# Generated by Django 3.0.8 on 2020-09-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_forum_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='last_activity',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
