# Generated by Django 3.0.8 on 2020-08-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200828_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
