# Generated by Django 3.0.8 on 2020-11-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201126_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='title',
            new_name='topic',
        ),
        migrations.AddField(
            model_name='videos',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
