# Generated by Django 3.0.8 on 2020-08-26 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200825_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='trainers',
        ),
        migrations.DeleteModel(
            name='LanguageTrainer',
        ),
    ]
