# Generated by Django 3.0.8 on 2020-11-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201126_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='video',
            new_name='pdf',
        ),
    ]
