# Generated by Django 3.0.8 on 2020-09-01 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200901_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='last_activity',
        ),
    ]
