# Generated by Django 3.0.8 on 2020-10-26 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Course'),
        ),
    ]
