# Generated by Django 3.0.8 on 2020-09-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_forum_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='slug',
        ),
        migrations.AlterField(
            model_name='forum',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
