# Generated by Django 3.0.8 on 2020-08-29 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200829_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
