# Generated by Django 3.0.8 on 2020-09-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200901_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='creator',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
