# Generated by Django 3.0.8 on 2020-08-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_assignment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='langauges_learnt',
        ),
        migrations.AddField(
            model_name='student',
            name='languages_learnt',
            field=models.ManyToManyField(blank=True, null=True, related_name='knowing_students', to='core.Language'),
        ),
        migrations.AlterField(
            model_name='student',
            name='languages_to_learn',
            field=models.ManyToManyField(blank=True, null=True, related_name='learning_students', to='core.Language'),
        ),
    ]
