# Generated by Django 3.0.8 on 2020-08-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200805_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='languages_known',
        ),
        migrations.AddField(
            model_name='language',
            name='trainers',
            field=models.ManyToManyField(related_name='languages', to='core.Trainer'),
        ),
    ]
