# Generated by Django 3.0.8 on 2020-08-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200829_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='note',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
