# Generated by Django 3.0.8 on 2020-08-05 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200805_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='trainers',
        ),
        migrations.AddField(
            model_name='course',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Trainer'),
        ),
    ]
