# Generated by Django 3.0.8 on 2020-08-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200805_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='completed_percent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='enddate',
            field=models.DateField(null=True),
        ),
    ]
