# Generated by Django 3.0.8 on 2020-08-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200806_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='languages_learnt',
            field=models.ManyToManyField(blank=True, related_name='knowing_students', to='core.Language'),
        ),
        migrations.AlterField(
            model_name='student',
            name='languages_to_learn',
            field=models.ManyToManyField(blank=True, related_name='learning_students', to='core.Language'),
        ),
    ]
