# Generated by Django 3.0.8 on 2020-08-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200820_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageTrainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages_to_teach', models.ManyToManyField(blank=True, related_name='knowing_teachers', to='core.Language')),
                ('trainers', models.ManyToManyField(related_name='languagetrainer', to='core.Trainer')),
            ],
        ),
    ]
