# Generated by Django 3.0.8 on 2020-08-20 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_languagetrainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Trainer'),
        ),
    ]
